import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider/ReduxProvider";
import Header from "./_components/Header/page";
import { ThemeProvider } from "./providers/theme-provider";

const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export const metadata: Metadata = {
  title: "Todos-Redux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={rajdhani.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <Header />
            {children}
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
