import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider/ReduxProvider";

const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export const metadata: Metadata = {
  title: "Todos-Redux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
